apiVersion: apps/v1
kind: Deployment
metadata:
  name: proyectoactividaddos-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: proyectoactividaddos
  template:
    metadata:
      labels:
        app: proyectoactividaddos
    spec:
      containers:
      - name: proyectoactividaddos
        image: alejocruzutb/proyectoactividaddos:latest
        ports:
        - containerPort: 8500
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"