apiVersion: v1
kind: Service
metadata:
  name: proyectoactividaddos-service
spec:
  type: NodePort
  selector:
    app: proyectoactividaddos
  ports:
  - protocol: TCP
    port: 8500
    targetPort: 8500
    nodePort: 30007
  type: LoadBalancer 